name: github actions for release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Debug version
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: echo "$VERSION"
    # - name: Checkout
    #   uses: actions/checkout@v2
    # - name: Build
    #   run: |
    #     echo "Action: Run Build and GITHUB_WORKSPACE env: $GITHUB_WORKSPACE"
    #     sudo /bin/bash $GITHUB_WORKSPACE/build.sh $GITHUB_WORKSPACE
    #     echo "Action: Run Build finished."
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: target/code-server-extensions-3.9.1.tar.gz
    #   env:
    #     GITHUB_WORKSPACE: $GITHUB_WORKSPACE
    #     FINAL_NAME: code-server-extensions-3.9.1
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
