name: github actions for release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        echo "Action: Run Build and GITHUB_WORKSPACE env: $GITHUB_WORKSPACE"
        sudo /bin/bash $GITHUB_WORKSPACE/build.sh $GITHUB_WORKSPACE
        echo "Action: Run Build finished."
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: $GITHUB_WORKSPACE/target/$FINAL_NAME.tar.gz
      env:
        GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        FINAL_NAME: code-server-extensions-3.9.1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
