name: Ci Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Regist code-server version
      id: code_server_version
      run: |
        code_server_version=$(cat CODE_SERVER_VERSION)
        echo "code_server_version=${code_server_version}" >> $GITHUB_ENV

    - name: Build
      run: |
        echo "Action: Run Build and GITHUB_WORKSPACE env: $GITHUB_WORKSPACE"
        sudo /bin/bash $GITHUB_WORKSPACE/build.sh $GITHUB_WORKSPACE ${{ env.code_server_version }}
        echo "Action: Run Build finished."
